name: sagemaker-studio
path: modules/ml/sagemaker-studio
parameters:
  - name: vpc_id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: subnet_ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: PrivateSubnetIds
  - name: data_science_users
    value:
    - ds-user-1
  - name: lead_data_science_users
    value:
    - lead-ds-user-1
  - name: server_lifecycle_name
    value: studio-auto-shutdown-2
  - name: studio_bucket_name
    value: mlops-*
  - name: retain_efs
    value: 'False'